version: "3"
services:
  jwt_auth_service:
    build: .
    ports:
    - "3000:3000"
    depends_on:
    - mongo
    environment:
    - DB_HOST=mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - data-volume:/data/db
volumes:
  data-volume: